version: '3.3'
services:
    app:
        volumes:
            - .env:/app/.env
        container_name: app
        restart: always
        ports:
            - 3000:3000
        image: app-uptime:latest