version: '3.3'
services:
    app:
        volumes:
            - .env:/app/.env
        container_name: z_configapp
        restart: always
        ports:
            - 3000:3000
        image: configapp:latest