modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: ip4

  tcp:
    prober: tcp
    tcp:
      preferred_ip_protocol: ip4
      insecure_skip_verify: true
      
  icmp:
    prober: icmp
    icmp:
     preferred_ip_protocol: ip4

  dns:
    prober: dns
    dns:
      preferred_ip_protocol: ip4
