version: '3'
services:
  crabby:
    image: prom/blackbox-exporter:master
    container_name: blackbox
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./blackbox.yaml:/etc/blackbox/blackbox.yaml
