global:
scrape_interval: 15s
scrape_configs:
- job_name: 'blackbox-tcp'
  scrape_timeout: 15s
  scrape_interval: 15s
  metrics_path: /probe
  params:
    module: [tcp_connect]
  static_configs:
   - targets:
   asd
  relabel_configs:
   - source_labels: [__address__]
     target_label: __param_target
   - source_labels: [__param_target]
     target_label: tcp_test
   - target_label: __address__
     replacement: prometheus-blackbox-exporter:9115